improved(ci): Add new seps in pipeline for confirm all tests passed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,20 +55,29 @@ jobs:
         # échoue si le code n'est pas bien formaté
         # en local black corrige, en CI black vérifie seulement
 
-  # ─────────────────────────────────────────
-  # ÉTAPE 6 — Lancer les tests
-  # ─────────────────────────────────────────
-  test:
-    runs-on: ubuntu-latest
-    needs: ci # s'assure que l'étape "ci" a réussi avant de
-    steps:
       - name: Lancer les tests (pytest)
         run: uv run pytest tests/ -v
         # tests/ = cherche dans le dossier tests/
         # -v = verbose, affiche chaque test
 
       # ─────────────────────────────────────────
-      # ÉTAPE 7 — Vérifier que le module s'importe
+      # ÉTAPE 6 — Vérifier que le module s'importe
       # ─────────────────────────────────────────
       - name: Build check
         run: uv run python -c "import sys; sys.path.insert(0, 'src'); from water_quality_service import WaterQualityService; print('Build OK ✅')"
+
+  # ─────────────────────────────────────────
+  # ÉTAPE 7 — Valider que tous les tests ont réussi avant de marquer la CI comme réussie
+  # ─────────────────────────────────────────
+  ci-success:
+    runs-on: ubuntu-latest
+    needs: [ci] # s'assure que l'étape "ci" a réussi avant de continuer
+    if: always()
+    steps:
+      - name: Check all jobs passed
+        run: |
+          if [[ "${{ needs.ci.result }}" == "failure" ||; then
+            echo "One or more tests failed."
+            exit 1
+          fi
+          echo "All tests passed."
